name: CI Pipeline for Azure Databricks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Databricks CLI (Latest)
      run: |
        pip install --upgrade databricks-cli
        pip install --upgrade databricks-sdk  # Ensures latest authentication support

    - name: Authenticate Databricks CLI
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        databricks configure --host "$DATABRICKS_HOST" --token "$DATABRICKS_TOKEN"

    - name: Upload sample data to DBFS
      run: |
        databricks fs cp ./sample_sales.csv dbfs:/FileStore/sample_sales.csv --overwrite
